### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [bbqmatt/jamming#7]
Adding the ability to trigger the search function by pressing the enter button will indeed make the app faster to navigate. The technical design proposed for the enter key is correct. The only thin missing is how you would detect what key is being pressed with  `if(event.key === "enter")`. Also we should avoid using `document.getElementByID` if possible. The onKey attributes will take care of that. Using your description, we should have;
```
  handleEnter(event) {
    if(event.key === "enter") {
      this.search();
    }
}
```
and
`<input onKeyPress={this.handleEnter}/>`

**Comment by bbqmatt** [comment]
Is there a reason to avoid document.getElementById approach?

**Comment by mp1pro** [comment]
Reactjs is a shadow DOM, it does not access the DOM directly like jQuery, If you need to adjust the DOM directly, do so in the the lifecycle event `componentDidMount`, reference: https://reactjs.org/docs/react-component.html. 
For further help, contact a react adviser at http://codecademy.com
